version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app/backend
    command: java -jar ./build/libs/backend-0.0.1-SNAPSHOT.jar
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true