version: '3.8'
services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_seungchan
      MYSQL_ROOT_PASSWORD: tmdcks2416@
    ports:
      - 3306:3306

  backend:
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db_seungchan
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: tmdcks2416@
    ports:
      - 8080:8080
    depends_on:
      - mysqldb